export default {
  GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
  CHANGE_CATEGORY: "CHANGE_CATEGORY",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
};
